module.exports = {
    future: {
        // removeDeprecatedGapUtilities: true,
        // purgeLayersByDefault: true,
    },
    purge: ["./src/**/*.vue", "./public/**/*.html"],
    target: "ie11",
    prefix: "",
    important: false,
    separator: ":",
    presets: [],
    theme: {
        screens: {
            sm: "640px",
            md: "768px",
            lg: "1024px",
            xl: "1280px",
            xxl: "1600px"
        },
        colors: {
            transparent: "transparent",
            current: "currentColor",

            black: "#000",
            white: "#fff",

            gray: {
                100: "#dbdbdb",
                200: "#bbbbbb",
                300: "#9d9d9e",
                400: "#F4F4F4 ",
                500: "#F7F9FA",
                600: "#67757c",
                700: "#716969",
                800: "#333333",
                900: "#F3F1F1",
                1000: "#999999",
                1100: "#c9ccd6",
                1200: "#E7E7E7",
                1300: "#d9d9d9",
                1400: "#ddd",
                1500: "#E9E9E9",
                1600: "#F2F2F2",
                1700: "#DFE1E8",
                1800: "#a6a7a8",
                1900: "#FAFAFA",
                2000: "#6f6f6f",
                2100: "#e8e8e8",
                2200: "#666",
                2300: "#f9f9f9",
                2400: "#f1f1f1"
            },
            red: {
                100: "#ff6440",
                200: "#c62727",
                300: "#DB2900",
                400: "#ff6440",
                500: "#ff8f75",
            },
            orange: {
                100: "#fffaf0",
                200: "#feebc8",
                300: "#fbd38d",
                400: "#f6ad55",
                500: "#ed8936",
                600: "#dd6b20",
                700: "#c05621",
                800: "#9c4221",
                900: "#7b341e"
            },
            yellow: {
                100: "#b7791f",
                200: "#bd9515"
            },
            green: {
                100: "#06d186",
                200: "#2f855a"
            },
            teal: {
                100: "#e6fffa",
                200: "#b2f5ea",
                300: "#81e6d9",
                400: "#4fd1c5",
                500: "#38b2ac",
                600: "#319795",
                700: "#2c7a7b",
                800: "#285e61",
                900: "#234e52"
            },
            blue: {
                100: "#f6f9fd",
                200: "#126ae8",
                300: "#0077cc",
                400: "#25427c",
                500: "#2491df",
                600: "#2276B2",
                700: "#32AAFF",
                800: "#1070ca",
                900: "#242666",
                1000: "#8ab9e5",
                1100: "#001737",
                1200: "#d7e5ea",
                1300: "#B2DEFF",
                1400: "#1890ff",
                1500: "#E6F4FF",
                1600: "#66c0ff",
                1700: "#386fd3",
                1800: "#00ceff",
                1900: "#e5f4ff",
                2000: "#b3e0ff"
            },
            indigo: {
                100: "#ebf4ff",
                200: "#c3dafe",
                300: "#a3bffa",
                400: "#7f9cf5",
                500: "#667eea",
                600: "#5a67d8",
                700: "#4c51bf",
                800: "#434190",
                900: "#3c366b"
            },
            purple: {
                100: "#faf5ff",
                200: "#e9d8fd",
                300: "#d6bcfa",
                400: "#b794f4",
                500: "#9f7aea",
                600: "#805ad5",
                700: "#6b46c1",
                800: "#553c9a",
                900: "#44337a"
            },
            pink: {
                100: "#fff5f7",
                200: "#fed7e2",
                300: "#fbb6ce",
                400: "#f687b3",
                500: "#ed64a6",
                600: "#d53f8c",
                700: "#b83280",
                800: "#97266d",
                900: "#702459"
            }
        },
        spacing: {
            px: "1px",
            "-1": "-1px",
            "-2": "-2px",
            "-24": "-24px",
            "-32": "-32px",
            0: "0",
            1: "0.25rem",
            2: "0.5rem",
            3: "0.75rem",
            4: "4px",
            5: "5px",
            6: "1.5rem",
            7: "7px",
            8: "8px",
            10: "10px",
            12: "12px",
            14: "14px",
            15: "15px",
            16: "16px",
            17: "17px",
            18: "18px",
            19: "19px",
            25: "25px",
            28: "7rem",
            30: "30px",
            32: "32px",
            37: "37px",
            42: "9.3rem",
            48: "12rem",
            56: "56px",
            64: "16rem",
            20: "20px",
            22: "22px",
            23: "23px",
            24: "24px",
            26: "26px",
            27: "27px",
            28: "28px",
            30: "30px",
            33: "33px",
            35: "35px",
            38: "38px",
            39: "39px",
            40: "40px",
            44: "44px",
            47: "47px",
            50: "50px",
            60: "60px",
            62: "62px",
            67: "67px",
            70: "70px",
            72: "72px",
            75: "75px",
            80: "80px",
            85: "85px",
            90: "90px",
            91: "91px",
            100: "100px",
            102: "102px",
            104: "104px",
            106: "106px",
            108: "108px",
            110: "110px",
            112: "112px",
            114: "114px",
            120: "120px",
            126: "126px",
            132: "132px",
            136: "136px",
            138: "138px",
            140: "140px",
            150: "150px",
            155: "155px",
            163: "163px",
            164: "164px",
            167: "167px",
            170: "170px",
            172: "172px",
            174: "174px",
            180: "180px",
            183: "183px",
            184: "184px",
            192: "192px",
            196: "196px",
            200: "200px",
            204: "204px",
            210: "210px",
            237: "237px",
            242: "242px",
            244: "244px",
            260: "260px",
            270: "270px",
            278: "278px",
            280: "280px",
            285: "285px",
            286: "286px",
            357: "357px",
            330: "330px",
            360: "360px",
            376: "376px",
            397: "397px",
            400: "400px",
            410: "410px",
            500: "500px",
            530: "530px",
            627: "627px",
            750: "750px",
            900: "900px",
            1440: "1440px"
        },
        backgroundColor: theme => theme("colors"),
        backgroundImage: {
            none: "none",
            "gradient-to-t": "linear-gradient(to top, var(--gradient-color-stops))",
            "gradient-to-tr": "linear-gradient(to top right, var(--gradient-color-stops))",
            "gradient-to-r": "linear-gradient(to right, var(--gradient-color-stops))",
            "gradient-to-br": "linear-gradient(to bottom right, var(--gradient-color-stops))",
            "gradient-to-b": "linear-gradient(to bottom, var(--gradient-color-stops))",
            "gradient-to-bl": "linear-gradient(to bottom left, var(--gradient-color-stops))",
            "gradient-to-l": "linear-gradient(to left, var(--gradient-color-stops))",
            "gradient-to-tl": "linear-gradient(to top left, var(--gradient-color-stops))"
        },
        gradientColorStops: theme => theme("colors"),
        backgroundOpacity: theme => theme("opacity"),
        backgroundPosition: {
            bottom: "bottom",
            center: "center",
            left: "left",
            "left-bottom": "left bottom",
            "left-top": "left top",
            right: "right",
            "right-bottom": "right bottom",
            "right-top": "right top",
            top: "top"
        },
        backgroundSize: {
            auto: "auto",
            cover: "cover",
            contain: "contain"
        },
        borderColor: theme => ({
            ...theme("colors"),
            default: theme("colors.gray.300", "currentColor")
        }),
        borderOpacity: theme => theme("opacity"),
        borderRadius: {
            none: "0",
            sm: "0.125rem",
            default: "0.25rem",
            md: "0.375rem",
            lg: "0.5rem",
            4: "4px",
            8: "8px",
            10: "10px",
            "2xl": "1rem",
            "3xl": "1.5rem",
            full: "9999px"
        },
        borderWidth: {
            default: "1px",
            0: "0",
            2: "2px",
            4: "4px",
            8: "8px"
        },
        boxShadow: {
            xs: "0 0 0 1px rgba(0, 0, 0, 0.05)",
            sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
            default: "0 3px 3px 0 rgba(0, 0, 0, 0.04)",
            md: "0 2px 4px 0 rgba(0, 0, 0, 0.1)",
            lg: "0 2px 20px 0 rgba(0, 0, 0, 0.2);",
            xl: "2px 2px 20px 0 rgba(0, 0, 0, 0.1)",
            "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
            inner: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
            outline: "0 0 0 3px rgba(66, 153, 225, 0.5)",
            none: "none"
        },
        container: {},
        cursor: {
            auto: "auto",
            default: "default",
            pointer: "pointer",
            wait: "wait",
            text: "text",
            move: "move",
            "not-allowed": "not-allowed"
        },
        divideColor: theme => theme("borderColor"),
        divideOpacity: theme => theme("borderOpacity"),
        divideWidth: theme => theme("borderWidth"),
        fill: {
            current: "currentColor"
        },
        flex: {
            1: "1 1 0%",
            auto: "1 1 auto",
            initial: "0 1 auto",
            none: "none"
        },
        flexGrow: {
            0: "0",
            default: "1"
        },
        flexShrink: {
            0: "0",
            default: "1"
        },
        fontFamily: {
            sans: ["Noto Sans TC", "sans-serif"],
            serif: ["Georgia", "Cambria", '"Times New Roman"', "Times", "serif"],
            mono: ["Menlo", "Monaco", "Consolas", '"Liberation Mono"', '"Courier New"', "monospace"]
        },
        fontSize: {
            xs: "0.75rem",
            12: "12px",
            15: "15px",
            16: "16px",
            17: "17px",
            18: "18px",
            20: "20px",
            24: "24px",
            30: "30px",
            40: "40px",
            lg: "1.125rem",
            xl: "1.25rem",
            "2xl": "1.5rem",
            "3xl": "1.875rem",
            "4xl": "2.25rem",
            "5xl": "3rem",
            "6xl": "4rem"
        },
        fontWeight: {
            hairline: "100",
            thin: "200",
            light: "300",
            normal: "400",
            medium: "500",
            semibold: "600",
            bold: "700",
            extrabold: "800",
            black: "900"
        },
        height: theme => ({
            auto: "auto",
            ...theme("spacing"),
            full: "100%",
            screen: "100vh"
        }),
        inset: theme => ({
            0: "0",
            auto: "auto",
            "1/4": "25%",
            "1/2": "50%",
            full: "100%",
            ...theme("spacing")
        }),
        letterSpacing: {
            tighter: "-0.05em",
            tight: "-0.025em",
            normal: "0",
            wide: "0.025em",
            wider: "2.15px",
            widest: "0.1em"
        },
        lineHeight: theme => ({
            none: "1",
            tight: "1.25",
            snug: "1.375",
            normal: "1.5",
            relaxed: "1.625",
            loose: "2",
            3: ".75rem",
            4: "1rem",
            5: "1.25rem",
            6: "1.5rem",
            7: "1.75rem",
            8: "2rem",
            9: "2.25rem",
            10: "2.5rem",
            15: "15px",
            26: "26px",
            ...theme("spacing"),
        }),
        listStyleType: {
            none: "none",
            disc: "disc",
            decimal: "decimal"
        },
        margin: (theme, { negative }) => ({
            auto: "auto",
            ...theme("spacing"),
            ...negative(theme("spacing"))
        }),
        maxHeight: {
            full: "100%",
            screen: "100vh"
        },
        maxWidth: (theme, { breakpoints }) => ({
            none: "none",
            xs: "20rem",
            sm: "24rem",
            md: "28rem",
            lg: "32rem",
            xl: "36rem",
            "2xl": "42rem",
            "3xl": "48rem",
            "4xl": "56rem",
            "5xl": "64rem",
            "6xl": "72rem",
            full: "100%",
            ...breakpoints(theme("screens")),
            ...theme("spacing")
        }),
        minHeight: theme => ({
            0: "0",
            full: "100%",
            screen: "100vh",
            ...theme("spacing")
        }),
        minWidth: theme => ({
            0: "0",
            full: "100%",
            ...theme("spacing")
        }),
        objectPosition: {
            bottom: "bottom",
            center: "center",
            left: "left",
            "left-bottom": "left bottom",
            "left-top": "left top",
            right: "right",
            "right-bottom": "right bottom",
            "right-top": "right top",
            top: "top"
        },
        opacity: {
            0: "0",
            5: "0.05",
            10: "0.1",
            15: "0.15",
            20: "0.2",
            25: "0.25",
            30: "0.3",
            35: "0.35",
            40: "0.4",
            45: "0.45",
            50: "0.5",
            60: "0.6",
            70: "0.7",
            75: "0.75",
            80: "0.8",
            100: "1"
        },
        order: {
            first: "-9999",
            last: "9999",
            none: "0",
            1: "1",
            2: "2",
            3: "3",
            4: "4",
            5: "5",
            6: "6",
            7: "7",
            8: "8",
            9: "9",
            10: "10",
            11: "11",
            12: "12"
        },
        outline: {
            none: ["2px solid transparent", "2px"],
            white: ["2px dotted white", "2px"],
            black: ["2px dotted black", "2px"]
        },
        padding: theme => theme("spacing"),
        placeholderColor: theme => theme("colors"),
        placeholderOpacity: theme => theme("opacity"),
        space: (theme, { negative }) => ({
            ...theme("spacing"),
            ...negative(theme("spacing"))
        }),
        stroke: {
            current: "currentColor"
        },
        strokeWidth: {
            0: "0",
            1: "1",
            2: "2"
        },
        textColor: theme => theme("colors"),
        textOpacity: theme => theme("opacity"),
        width: theme => ({
            auto: "auto",
            ...theme("spacing"),
            "1/2": "50%",
            "1/3": "33.333333%",
            "2/3": "66.666667%",
            "1/4": "25%",
            "2/4": "50%",
            "3/4": "75%",
            "1/5": "20%",
            "2/5": "40%",
            "3/5": "60%",
            "4/5": "80%",
            "1/6": "16.666667%",
            "2/6": "33.333333%",
            "3/6": "50%",
            "4/6": "66.666667%",
            "5/6": "83.333333%",
            "1/12": "8.333333%",
            "2/12": "16.666667%",
            "3/12": "25%",
            "4/12": "33.333333%",
            "5/12": "41.666667%",
            "6/12": "50%",
            "7/12": "58.333333%",
            "8/12": "66.666667%",
            "9/12": "75%",
            "10/12": "83.333333%",
            "11/12": "91.666667%",
            full: "100%",
            screen: "100vw",
            navbarSize: "calc( 100% - 24px)"
        }),
        zIndex: {
            auto: "auto",
            "-1": "-1",
            0: "0",
            10: "10",
            20: "20",
            30: "30",
            40: "40",
            50: "50",
            100: "100"
        },
        gap: theme => theme("spacing"),
        gridTemplateColumns: {
            none: "none",
            1: "repeat(1, minmax(0, 1fr))",
            2: "repeat(2, minmax(0, 1fr))",
            3: "repeat(3, minmax(0, 1fr))",
            4: "repeat(4, minmax(0, 1fr))",
            5: "repeat(5, minmax(0, 1fr))",
            6: "repeat(6, minmax(0, 1fr))",
            7: "repeat(7, minmax(0, 1fr))",
            8: "repeat(8, minmax(0, 1fr))",
            9: "repeat(9, minmax(0, 1fr))",
            10: "repeat(10, minmax(0, 1fr))",
            11: "repeat(11, minmax(0, 1fr))",
            12: "repeat(12, minmax(0, 1fr))"
        },
        gridAutoColumns: {
            auto: "auto",
            min: "min-content",
            max: "max-content",
            fr: "minmax(0, 1fr)"
        },
        gridColumn: {
            auto: "auto",
            "span-1": "span 1 / span 1",
            "span-2": "span 2 / span 2",
            "span-3": "span 3 / span 3",
            "span-4": "span 4 / span 4",
            "span-5": "span 5 / span 5",
            "span-6": "span 6 / span 6",
            "span-7": "span 7 / span 7",
            "span-8": "span 8 / span 8",
            "span-9": "span 9 / span 9",
            "span-10": "span 10 / span 10",
            "span-11": "span 11 / span 11",
            "span-12": "span 12 / span 12",
            "span-full": "1 / -1"
        },
        gridColumnStart: {
            auto: "auto",
            1: "1",
            2: "2",
            3: "3",
            4: "4",
            5: "5",
            6: "6",
            7: "7",
            8: "8",
            9: "9",
            10: "10",
            11: "11",
            12: "12",
            13: "13"
        },
        gridColumnEnd: {
            auto: "auto",
            1: "1",
            2: "2",
            3: "3",
            4: "4",
            5: "5",
            6: "6",
            7: "7",
            8: "8",
            9: "9",
            10: "10",
            11: "11",
            12: "12",
            13: "13"
        },
        gridTemplateRows: {
            none: "none",
            1: "repeat(1, minmax(0, 1fr))",
            2: "repeat(2, minmax(0, 1fr))",
            3: "repeat(3, minmax(0, 1fr))",
            4: "repeat(4, minmax(0, 1fr))",
            5: "repeat(5, minmax(0, 1fr))",
            6: "repeat(6, minmax(0, 1fr))"
        },
        gridAutoRows: {
            auto: "auto",
            min: "min-content",
            max: "max-content",
            fr: "minmax(0, 1fr)"
        },
        gridRow: {
            auto: "auto",
            "span-1": "span 1 / span 1",
            "span-2": "span 2 / span 2",
            "span-3": "span 3 / span 3",
            "span-4": "span 4 / span 4",
            "span-5": "span 5 / span 5",
            "span-6": "span 6 / span 6",
            "span-full": "1 / -1"
        },
        gridRowStart: {
            auto: "auto",
            1: "1",
            2: "2",
            3: "3",
            4: "4",
            5: "5",
            6: "6",
            7: "7"
        },
        gridRowEnd: {
            auto: "auto",
            1: "1",
            2: "2",
            3: "3",
            4: "4",
            5: "5",
            6: "6",
            7: "7"
        },
        transformOrigin: {
            center: "center",
            top: "top",
            "top-right": "top right",
            right: "right",
            "bottom-right": "bottom right",
            bottom: "bottom",
            "bottom-left": "bottom left",
            left: "left",
            "top-left": "top left"
        },
        scale: {
            0: "0",
            50: ".5",
            75: ".75",
            90: ".9",
            95: ".95",
            100: "1",
            105: "1.05",
            110: "1.1",
            125: "1.25",
            150: "1.5"
        },
        rotate: {
            "-180": "-180deg",
            "-90": "-90deg",
            "-45": "-45deg",
            "-12": "-12deg",
            "-6": "-6deg",
            "-3": "-3deg",
            "-2": "-2deg",
            "-1": "-1deg",
            0: "0",
            1: "1deg",
            2: "2deg",
            3: "3deg",
            6: "6deg",
            12: "12deg",
            45: "45deg",
            90: "90deg",
            180: "180deg"
        },
        translate: (theme, { negative }) => ({
            ...theme("spacing"),
            ...negative(theme("spacing")),
            "-full": "-100%",
            "-1/2": "-50%",
            "-99/100": "-99%",
            "1/2": "50%",
            full: "100%",
            "99/100": "99%"
        }),
        skew: {
            "-12": "-12deg",
            "-6": "-6deg",
            "-3": "-3deg",
            "-2": "-2deg",
            "-1": "-1deg",
            0: "0",
            1: "1deg",
            2: "2deg",
            3: "3deg",
            6: "6deg",
            12: "12deg"
        },
        transitionProperty: {
            none: "none",
            all: "all",
            default: "background-color, border-color, color, fill, stroke, opacity, box-shadow, transform",
            colors: "background-color, border-color, color, fill, stroke",
            opacity: "opacity",
            shadow: "box-shadow",
            transform: "transform"
        },
        transitionTimingFunction: {
            linear: "linear",
            in: "cubic-bezier(0.4, 0, 1, 1)",
            out: "cubic-bezier(0, 0, 0.2, 1)",
            "in-out": "cubic-bezier(0.4, 0, 0.2, 1)"
        },
        transitionDuration: {
            75: "75ms",
            100: "100ms",
            150: "150ms",
            200: "200ms",
            300: "300ms",
            500: "500ms",
            700: "700ms",
            1000: "1000ms"
        },
        transitionDelay: {
            75: "75ms",
            100: "100ms",
            150: "150ms",
            200: "200ms",
            300: "300ms",
            500: "500ms",
            700: "700ms",
            1000: "1000ms"
        },
        animation: {
            none: "none",
            spin: "spin 1s linear infinite",
            ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
            pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
            bounce: "bounce 1s infinite"
        },
        keyframes: {
            spin: {
                to: { transform: "rotate(360deg)" }
            },
            ping: {
                "75%, 100%": { transform: "scale(2)", opacity: "0" }
            },
            pulse: {
                "50%": { opacity: ".5" }
            },
            bounce: {
                "0%, 100%": {
                    transform: "translateY(-25%)",
                    animationTimingFunction: "cubic-bezier(0.8,0,1,1)"
                },
                "50%": {
                    transform: "none",
                    animationTimingFunction: "cubic-bezier(0,0,0.2,1)"
                }
            }
        }
    },
    variants: {
        accessibility: ["responsive", "focus"],
        alignContent: ["responsive"],
        alignItems: ["responsive"],
        alignSelf: ["responsive"],
        appearance: ["responsive"],
        backgroundAttachment: ["responsive"],
        backgroundClip: ["responsive"],
        backgroundColor: ["responsive", "hover", "focus", "disabled"],
        backgroundImage: ["responsive"],
        gradientColorStops: ["responsive", "hover", "focus"],
        backgroundOpacity: ["responsive", "hover", "focus"],
        backgroundPosition: ["responsive"],
        backgroundRepeat: ["responsive"],
        backgroundSize: ["responsive"],
        borderCollapse: ["responsive"],
        borderColor: ["responsive", "hover", "active", "focus"],
        borderOpacity: ["responsive", "hover", "focus"],
        borderRadius: ["responsive"],
        borderStyle: ["responsive"],
        borderWidth: ["responsive", "hover", "active"],
        boxShadow: ["responsive", "hover", "focus"],
        boxSizing: ["responsive"],
        container: ["responsive"],
        cursor: ["responsive"],
        display: ["responsive"],
        divideColor: ["responsive"],
        divideOpacity: ["responsive"],
        divideStyle: ["responsive"],
        divideWidth: ["responsive"],
        fill: ["responsive"],
        flex: ["responsive"],
        flexDirection: ["responsive"],
        flexGrow: ["responsive"],
        flexShrink: ["responsive"],
        flexWrap: ["responsive"],
        float: ["responsive"],
        clear: ["responsive"],
        fontFamily: ["responsive"],
        fontSize: ["responsive"],
        fontSmoothing: ["responsive"],
        fontVariantNumeric: ["responsive"],
        fontStyle: ["responsive"],
        fontWeight: ["responsive", "hover", "focus"],
        height: ["responsive"],
        inset: ["responsive"],
        justifyContent: ["responsive"],
        justifyItems: ["responsive"],
        justifySelf: ["responsive"],
        letterSpacing: ["responsive"],
        lineHeight: ["responsive"],
        listStylePosition: ["responsive"],
        listStyleType: ["responsive"],
        margin: ["responsive"],
        maxHeight: ["responsive"],
        maxWidth: ["responsive"],
        minHeight: ["responsive"],
        minWidth: ["responsive"],
        objectFit: ["responsive"],
        objectPosition: ["responsive"],
        opacity: ["responsive", "hover", "focus"],
        order: ["responsive"],
        outline: ["responsive", "focus"],
        overflow: ["responsive"],
        overscrollBehavior: ["responsive"],
        padding: ["responsive"],
        placeContent: ["responsive"],
        placeItems: ["responsive"],
        placeSelf: ["responsive"],
        placeholderColor: ["responsive", "focus"],
        placeholderOpacity: ["responsive", "focus"],
        pointerEvents: ["responsive"],
        position: ["responsive"],
        resize: ["responsive"],
        space: ["responsive"],
        stroke: ["responsive"],
        strokeWidth: ["responsive"],
        tableLayout: ["responsive"],
        textAlign: ["responsive"],
        textColor: ["responsive", "hover", "focus"],
        textOpacity: ["responsive", "hover", "focus"],
        textDecoration: ["responsive", "hover", "focus"],
        textTransform: ["responsive"],
        userSelect: ["responsive"],
        verticalAlign: ["responsive"],
        visibility: ["responsive"],
        whitespace: ["responsive"],
        width: ["responsive"],
        wordBreak: ["responsive"],
        zIndex: ["responsive"],
        gap: ["responsive"],
        gridAutoFlow: ["responsive"],
        gridTemplateColumns: ["responsive"],
        gridAutoColumns: ["responsive"],
        gridColumn: ["responsive"],
        gridColumnStart: ["responsive"],
        gridColumnEnd: ["responsive"],
        gridTemplateRows: ["responsive"],
        gridAutoRows: ["responsive"],
        gridRow: ["responsive"],
        gridRowStart: ["responsive"],
        gridRowEnd: ["responsive"],
        transform: ["responsive"],
        transformOrigin: ["responsive"],
        scale: ["responsive", "hover", "focus"],
        rotate: ["responsive", "hover", "focus"],
        translate: ["responsive", "hover", "focus"],
        skew: ["responsive", "hover", "focus"],
        transitionProperty: ["responsive"],
        transitionTimingFunction: ["responsive"],
        transitionDuration: ["responsive"],
        transitionDelay: ["responsive"],
        animation: ["responsive"]
    },
    corePlugins: {},
    plugins: []
};